In [33]:
import pandas as pd
import numpy as np

In [34]:
data = pd.read_csv('paises (2).csv',sep=';')

display(data)

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,48.0,0.00,23.06,163.07,700,36.0,3.2,12.13,0.22,87.65,1.0,46.60,20.34,0.380,0.240,0.380
1,Albania,EASTERN EUROPE,3581655,28748,124.6,1.26,-4.93,21.52,4500,86.5,71.2,21.09,4.42,74.49,3.0,15.11,5.22,0.232,0.188,0.579
2,Algeria,NORTHERN AFRICA,32930091,2381740,13.8,0.04,-0.39,31.00,6000,70.0,78.1,3.22,0.25,96.53,1.0,17.14,4.61,0.101,0.600,0.298
3,American Samoa,OCEANIA,57794,199,290.4,58.29,-20.71,9.27,8000,97.0,259.5,10.00,15.00,75.00,2.0,22.46,3.27,0.000,0.000,0.000
4,Andorra,WESTERN EUROPE,71201,468,152.1,0.00,6.60,4.05,19000,100.0,497.2,2.22,0.00,97.78,3.0,8.71,6.25,0.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,West Bank,NEAR EAST,2460492,5860,419.9,0.00,2.98,19.62,800,0.0,145.2,16.90,18.97,64.13,3.0,31.67,3.92,0.090,0.280,0.630
223,Western Sahara,NORTHERN AFRICA,273008,266000,1.0,0.42,0.00,0.00,0,0.0,0.0,0.02,0.00,99.98,1.0,0.00,0.00,0.000,0.000,0.400
224,Yemen,NEAR EAST,21456188,527970,40.6,0.36,0.00,61.50,800,50.2,37.2,2.78,0.24,96.98,1.0,42.89,8.30,0.135,0.472,0.393
225,Zambia,SUB-SAHARAN AFRICA,11502010,752614,15.3,0.00,0.00,88.29,800,80.6,8.2,7.08,0.03,92.90,2.0,41.00,19.93,0.220,0.290,0.489
226,Zimbabwe,SUB-SAHARAN AFRICA,12236805,390580,31.3,0.00,0.00,67.69,1900,90.7,26.8,8.32,0.34,91.34,2.0,28.01,21.84,0.179,0.243,0.579

In [35]:
print(f"Colunas : \n{data.columns}")

print(f"Ver ponta superior : \n{data.head(5)}")

print(f"Ver ponta inferior : \n{data.tail(3)}")

Colunas :
Index(['Country', 'Region', 'Population', 'Area (sq. mi.)',
       'Pop. Density (per sq. mi.)', 'Coastline (coast/area ratio)',
       'Net migration', 'Infant mortality (per 1000 births)',
       'GDP ($ per capita)', 'Literacy (%)', 'Phones (per 1000)', 'Arable (%)',
       'Crops (%)', 'Other (%)', 'Climate', 'Birthrate', 'Deathrate',
       'Agriculture', 'Industry', 'Service'],
      dtype='object')
Ver ponta superior :
           Country                               Region  Population  \
0     Afghanistan         ASIA (EX. NEAR EAST)             31056997
1         Albania   EASTERN EUROPE                          3581655
2         Algeria   NORTHERN AFRICA                        32930091
3  American Samoa   OCEANIA                                   57794
4         Andorra   WESTERN EUROPE                            71201

   Area (sq. mi.)  Pop. Density (per sq. mi.)  Coastline (coast/area ratio)  \
0          647500                        48.0                          0.00
1           28748                       124.6                          1.26
2         2381740                        13.8                          0.04
3             199                       290.4                         58.29
4             468                       152.1                          0.00

   Net migration  Infant mortality (per 1000 births)  GDP ($ per capita)  \
0          23.06                              163.07                 700
1          -4.93                               21.52                4500
2          -0.39                               31.00                6000
3         -20.71                                9.27                8000
4           6.60                                4.05               19000

   Literacy (%)  Phones (per 1000)  Arable (%)  Crops (%)  Other (%)  Climate  \
0          36.0                3.2       12.13       0.22      87.65      1.0
1          86.5               71.2       21.09       4.42      74.49      3.0
2          70.0               78.1        3.22       0.25      96.53      1.0
3          97.0              259.5       10.00      15.00      75.00      2.0
4         100.0              497.2        2.22       0.00      97.78      3.0

   Birthrate  Deathrate  Agriculture  Industry  Service
0      46.60      20.34        0.380     0.240    0.380
1      15.11       5.22        0.232     0.188    0.579
2      17.14       4.61        0.101     0.600    0.298
3      22.46       3.27        0.000     0.000    0.000
4       8.71       6.25        0.000     0.000    0.000
Ver ponta inferior :
       Country                               Region  Population  \
224     Yemen   NEAR EAST                              21456188
225    Zambia   SUB-SAHARAN AFRICA                     11502010
226  Zimbabwe   SUB-SAHARAN AFRICA                     12236805

     Area (sq. mi.)  Pop. Density (per sq. mi.)  Coastline (coast/area ratio)  \
224          527970                        40.6                          0.36
225          752614                        15.3                          0.00
226          390580                        31.3                          0.00

     Net migration  Infant mortality (per 1000 births)  GDP ($ per capita)  \
224            0.0                               61.50                 800
225            0.0                               88.29                 800
226            0.0                               67.69                1900

     Literacy (%)  Phones (per 1000)  Arable (%)  Crops (%)  Other (%)  \
224          50.2               37.2        2.78       0.24      96.98
225          80.6                8.2        7.08       0.03      92.90
226          90.7               26.8        8.32       0.34      91.34

     Climate  Birthrate  Deathrate  Agriculture  Industry  Service
224      1.0      42.89       8.30        0.135     0.472    0.393
225      2.0      41.00      19.93        0.220     0.290    0.489
226      2.0      28.01      21.84        0.179     0.243    0.579

Slicing no dataset

In [36]:
print(f"Colunas : \n{data.columns}")

print(f"Pegando colunas específicas : \n{data[["Region","Climate","Service"]]}")

Colunas :
Index(['Country', 'Region', 'Population', 'Area (sq. mi.)',
       'Pop. Density (per sq. mi.)', 'Coastline (coast/area ratio)',
       'Net migration', 'Infant mortality (per 1000 births)',
       'GDP ($ per capita)', 'Literacy (%)', 'Phones (per 1000)', 'Arable (%)',
       'Crops (%)', 'Other (%)', 'Climate', 'Birthrate', 'Deathrate',
       'Agriculture', 'Industry', 'Service'],
      dtype='object')
Pegando colunas específicas :
                                  Region  Climate  Service
0          ASIA (EX. NEAR EAST)               1.0    0.380
1    EASTERN EUROPE                           3.0    0.579
2    NORTHERN AFRICA                          1.0    0.298
3    OCEANIA                                  2.0    0.000
4    WESTERN EUROPE                           3.0    0.000
..                                   ...      ...      ...
222  NEAR EAST                                3.0    0.630
223  NORTHERN AFRICA                          1.0    0.400
224  NEAR EAST                                1.0    0.393
225  SUB-SAHARAN AFRICA                       2.0    0.489
226  SUB-SAHARAN AFRICA                       2.0    0.579

[227 rows x 3 columns]

Separando arquivo original em novos arquivos

In [37]:
total_population = np.sum(data["Population"])
print(f"Total população mundial : {total_population}")

seriesPercent = (data["Population"] / total_population) * 100

print("Adicionando porcentagem no dataset")
data["%Population"] = np.round(seriesPercent, 2)

display(data)

print("Criando nova versão do arquivo")
data.to_csv("paises_v2")

print(f"País com maior população : \n{data.nlargest(5,"%Population")}")
print(f"Nomes dos países com maior população : \n{data.nlargest(5,"%Population")["Country"]}")
print(f"Nome dos países com menor população : \n{data.nsmallest(5,"%Population")["Country"]}")

Total população mundial : 6524044551
Adicionando porcentagem no dataset

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),...,Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service,%Population
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,48.0,0.00,23.06,163.07,700,36.0,...,12.13,0.22,87.65,1.0,46.60,20.34,0.380,0.240,0.380,0.48
1,Albania,EASTERN EUROPE,3581655,28748,124.6,1.26,-4.93,21.52,4500,86.5,...,21.09,4.42,74.49,3.0,15.11,5.22,0.232,0.188,0.579,0.05
2,Algeria,NORTHERN AFRICA,32930091,2381740,13.8,0.04,-0.39,31.00,6000,70.0,...,3.22,0.25,96.53,1.0,17.14,4.61,0.101,0.600,0.298,0.50
3,American Samoa,OCEANIA,57794,199,290.4,58.29,-20.71,9.27,8000,97.0,...,10.00,15.00,75.00,2.0,22.46,3.27,0.000,0.000,0.000,0.00
4,Andorra,WESTERN EUROPE,71201,468,152.1,0.00,6.60,4.05,19000,100.0,...,2.22,0.00,97.78,3.0,8.71,6.25,0.000,0.000,0.000,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,West Bank,NEAR EAST,2460492,5860,419.9,0.00,2.98,19.62,800,0.0,...,16.90,18.97,64.13,3.0,31.67,3.92,0.090,0.280,0.630,0.04
223,Western Sahara,NORTHERN AFRICA,273008,266000,1.0,0.42,0.00,0.00,0,0.0,...,0.02,0.00,99.98,1.0,0.00,0.00,0.000,0.000,0.400,0.00
224,Yemen,NEAR EAST,21456188,527970,40.6,0.36,0.00,61.50,800,50.2,...,2.78,0.24,96.98,1.0,42.89,8.30,0.135,0.472,0.393,0.33
225,Zambia,SUB-SAHARAN AFRICA,11502010,752614,15.3,0.00,0.00,88.29,800,80.6,...,7.08,0.03,92.90,2.0,41.00,19.93,0.220,0.290,0.489,0.18
226,Zimbabwe,SUB-SAHARAN AFRICA,12236805,390580,31.3,0.00,0.00,67.69,1900,90.7,...,8.32,0.34,91.34,2.0,28.01,21.84,0.179,0.243,0.579,0.19

Criando nova versão do arquivo
País com maior população :
            Country                               Region  Population  \
42           China         ASIA (EX. NEAR EAST)           1313973713
94           India         ASIA (EX. NEAR EAST)           1095351995
214  United States   NORTHERN AMERICA                      298444215
95       Indonesia         ASIA (EX. NEAR EAST)            245452739
27          Brazil               LATIN AMER. & CARIB       188078227

     Area (sq. mi.)  Pop. Density (per sq. mi.)  Coastline (coast/area ratio)  \
42          9596960                       136.9                          0.15
94          3287590                       333.2                          0.21
214         9631420                        31.0                          0.21
95          1919440                       127.9                          2.85
27          8511965                        22.1                          0.09

     Net migration  Infant mortality (per 1000 births)  GDP ($ per capita)  \
42           -0.40                               24.18                5000
94           -0.07                               56.29                2900
214           3.41                                6.50               37800
95            0.00                               35.60                3200
27           -0.03                               29.61                7600

     Literacy (%)  ...  Arable (%)  Crops (%)  Other (%)  Climate  Birthrate  \
42           90.9  ...       15.40       1.25      83.35      1.5      13.25
94           59.5  ...       54.40       2.74      42.86      2.5      22.01
214          97.0  ...       19.13       0.22      80.65      3.0      14.14
95           87.9  ...       11.32       7.23      81.45      2.0      20.34
27           86.4  ...        6.96       0.90      92.15      2.0      16.56

     Deathrate  Agriculture  Industry  Service  %Population
42        6.97        0.125     0.473    0.403        20.14
94        8.18        0.186     0.276    0.538        16.79
214       8.26        0.010     0.204    0.787         4.57
95        6.25        0.134     0.458    0.408         3.76
27        6.17        0.084     0.400    0.516         2.88

[5 rows x 21 columns]
Nomes dos países com maior população :
42             China
94             India
214    United States
95         Indonesia
27            Brazil
Name: Country, dtype: object
Nome dos países com menor população :
3        American Samoa
4               Andorra
6              Anguilla
7     Antigua & Barbuda
10                Aruba
Name: Country, dtype: object

Agrupamento de dados - Dados categóricos

In [46]:
print(f"Agrupando por região somando as medidas : \n{data.groupby("Region").sum()}")
grupo_region = data.groupby("Region")
print(f"Países por região : \n{grupo_region.count()["Country"]} ")
print(f"População por região : \n{grupo_region.sum()["Population"]}")

Agrupando por região somando as medidas :
                                                                               Country  \
Region
ASIA (EX. NEAR EAST)                 Afghanistan Bangladesh Bhutan Brunei Burma Cam...
BALTICS                                                      Estonia Latvia Lithuania
C.W. OF IND. STATES                  Armenia Azerbaijan Belarus Georgia Kazakhstan ...
EASTERN EUROPE                       Albania Bosnia & Herzegovina Bulgaria Croatia ...
LATIN AMER. & CARIB                  Anguilla Antigua & Barbuda Argentina Aruba Bah...
NEAR EAST                            Bahrain Cyprus Gaza Strip Iraq Israel Jordan K...
NORTHERN AFRICA                      Algeria Egypt Libya Morocco Tunisia Western Sa...
NORTHERN AMERICA                     Bermuda Canada Greenland St Pierre & Miquelon ...
OCEANIA                              American Samoa Australia Cook Islands Fiji Fre...
SUB-SAHARAN AFRICA                   Angola Benin Botswana Burkina Faso Burundi Cam...
WESTERN EUROPE                       Andorra Austria Belgium Denmark Faroe Islands ...

                                     Population  Area (sq. mi.)  \
Region
ASIA (EX. NEAR EAST)                 3687982236        23096712
BALTICS                                 7184974          175015
C.W. OF IND. STATES                   280081548        22100843
EASTERN EUROPE                        119914717         1152222
LATIN AMER. & CARIB                   561824599        20544084
NEAR EAST                             195068377         4355586
NORTHERN AFRICA                       161407133         6018890
NORTHERN AMERICA                      331672307        21782471
OCEANIA                                33131662         8519812
SUB-SAHARAN AFRICA                    749437000        24341406
WESTERN EUROPE                        396339998         3710478

                                     Pop. Density (per sq. mi.)  \
Region
ASIA (EX. NEAR EAST)                                    35415.1
BALTICS                                                   119.5
C.W. OF IND. STATES                                       680.5
EASTERN EUROPE                                           1210.8
LATIN AMER. & CARIB                                      6129.1
NEAR EAST                                                6833.3
NORTHERN AFRICA                                           233.6
NORTHERN AMERICA                                         1304.3
OCEANIA                                                  2754.8
SUB-SAHARAN AFRICA                                       4705.5
WESTERN EUROPE                                          26657.2

                                     Coastline (coast/area ratio)  \
Region
ASIA (EX. NEAR EAST)                                       501.95
BALTICS                                                      9.35
C.W. OF IND. STATES                                          1.12
EASTERN EUROPE                                              12.42
LATIN AMER. & CARIB                                        718.75
NEAR EAST                                                   57.64
NORTHERN AFRICA                                              1.91
NORTHERN AMERICA                                           248.20
OCEANIA                                                   2265.60
SUB-SAHARAN AFRICA                                         260.41
WESTERN EUROPE                                             727.18

                                     Net migration  \
Region
ASIA (EX. NEAR EAST)                         38.43
BALTICS                                      -6.10
C.W. OF IND. STATES                         -24.40
EASTERN EUROPE                               -7.77
LATIN AMER. & CARIB                         -67.25
NEAR EAST                                    42.40
NORTHERN AFRICA                              -2.16
NORTHERN AMERICA                             -1.37
OCEANIA                                     -39.15
SUB-SAHARAN AFRICA                          -17.09
WESTERN EUROPE                               93.00

                                     Infant mortality (per 1000 births)  \
Region
ASIA (EX. NEAR EAST)                                            1169.84
BALTICS                                                           24.31
C.W. OF IND. STATES                                              532.92
EASTERN EUROPE                                                   152.24
LATIN AMER. & CARIB                                              904.17
NEAR EAST                                                        374.04
NORTHERN AFRICA                                                  154.58
NORTHERN AMERICA                                                  43.14
OCEANIA                                                          383.87
SUB-SAHARAN AFRICA                                              4082.00
WESTERN EUROPE                                                   132.45

                                     GDP ($ per capita)  Literacy (%)  \
Region
ASIA (EX. NEAR EAST)                             225500        2227.5
BALTICS                                           33900         299.2
C.W. OF IND. STATES                               48000        1184.7
EASTERN EUROPE                                   117700         873.8
LATIN AMER. & CARIB                              390700        3988.8
NEAR EAST                                        167300        1113.3
NORTHERN AFRICA                                   27300         336.2
NORTHERN AMERICA                                 130500         391.0
OCEANIA                                          173200        1510.2
SUB-SAHARAN AFRICA                               118500        3125.5
WESTERN EUROPE                                   757300        2263.0

                                     Phones (per 1000)  Arable (%)  Crops (%)  \
Region
ASIA (EX. NEAR EAST)                            4621.3      444.49     107.77
BALTICS                                          878.6       90.93       1.83
C.W. OF IND. STATES                             1966.2      233.45      24.27
EASTERN EUROPE                                  3369.0      371.79      29.17
LATIN AMER. & CARIB                            11953.1      485.59     221.11
NEAR EAST                                       3136.7      168.86      81.69
NORTHERN AFRICA                                  501.0       44.61      16.83
NORTHERN AMERICA                                3433.7       57.13       0.24
OCEANIA                                         3987.6      161.01     309.11
SUB-SAHARAN AFRICA                              2167.9      589.29     189.44
WESTERN EUROPE                                 16626.6      457.20      45.49

                                     Other (%)  Climate  Birthrate  Deathrate  \
Region
ASIA (EX. NEAR EAST)                   2247.74     53.0     592.42     213.84
BALTICS                                 207.24      6.0      28.03      37.89
C.W. OF IND. STATES                     942.28     25.5     214.27     124.10
EASTERN EUROPE                          799.05     28.0     114.08     113.13
LATIN AMER. & CARIB                    3793.31     91.5     858.65     286.92
NEAR EAST                              1349.33     25.0     400.51      76.95
NORTHERN AFRICA                         538.56      6.0     104.07      24.03
NORTHERN AMERICA                        442.63      6.0      65.77      38.47
OCEANIA                                1629.88     42.0     442.16     110.40
SUB-SAHARAN AFRICA                     4221.29     90.5    1838.24     773.16
WESTERN EUROPE                         2197.31     65.0     295.50     261.93

                                     Agriculture  Industry  Service  \
Region
ASIA (EX. NEAR EAST)                       4.974     8.460   14.563
BALTICS                                    0.135     0.880    1.985
C.W. OF IND. STATES                        2.304     3.936    5.762
EASTERN EUROPE                             1.106     3.711    7.184
LATIN AMER. & CARIB                        3.914    11.013   27.981
NEAR EAST                                  1.021     6.496    8.480
NORTHERN AFRICA                            0.675     2.131    2.592
NORTHERN AMERICA                           0.042     0.598    2.361
OCEANIA                                    2.802     3.444    9.743
SUB-SAHARAN AFRICA                        13.894    13.077   22.038
WESTERN EUROPE                             1.112     5.906   17.151

                                     %Population
Region
ASIA (EX. NEAR EAST)                       56.52
BALTICS                                     0.10
C.W. OF IND. STATES                         4.30
EASTERN EUROPE                              1.82
LATIN AMER. & CARIB                         8.58
NEAR EAST                                   2.99
NORTHERN AFRICA                             2.47
NORTHERN AMERICA                            5.08
OCEANIA                                     0.48
SUB-SAHARAN AFRICA                         11.50
WESTERN EUROPE                              6.06
Países por região :
Region
ASIA (EX. NEAR EAST)                   28
BALTICS                                 3
C.W. OF IND. STATES                    12
EASTERN EUROPE                         12
LATIN AMER. & CARIB                    45
NEAR EAST                              16
NORTHERN AFRICA                         6
NORTHERN AMERICA                        5
OCEANIA                                21
SUB-SAHARAN AFRICA                     51
WESTERN EUROPE                         28
Name: Country, dtype: int64
População por região :
Region
ASIA (EX. NEAR EAST)                   3687982236
BALTICS                                   7184974
C.W. OF IND. STATES                     280081548
EASTERN EUROPE                          119914717
LATIN AMER. & CARIB                     561824599
NEAR EAST                               195068377
NORTHERN AFRICA                         161407133
NORTHERN AMERICA                        331672307
OCEANIA                                  33131662
SUB-SAHARAN AFRICA                      749437000
WESTERN EUROPE                          396339998
Name: Population, dtype: int64

Criando funções customizadas

In [47]:
def tenPercent(x):
  return x*0.9

90.0

In [53]:
display(data.columns)

taxa_mortalidade = data["Deathrate"]

print(f"Aplicando função customizada : \n{taxa_mortalidade.apply(tenPercent)}")

print("Adicionando nova coluna no dataset")

data["Deathrate - 10%"] = taxa_mortalidade.apply(tenPercent)

display(data)

Index(['Country', 'Region', 'Population', 'Area (sq. mi.)',
       'Pop. Density (per sq. mi.)', 'Coastline (coast/area ratio)',
       'Net migration', 'Infant mortality (per 1000 births)',
       'GDP ($ per capita)', 'Literacy (%)', 'Phones (per 1000)', 'Arable (%)',
       'Crops (%)', 'Other (%)', 'Climate', 'Birthrate', 'Deathrate',
       'Agriculture', 'Industry', 'Service', '%Population'],
      dtype='object')

Aplicando função customizada :
0      18.306
1       4.698
2       4.149
3       2.943
4       5.625
        ...
222     3.528
223     0.000
224     7.470
225    17.937
226    19.656
Name: Deathrate, Length: 227, dtype: float64
Adicionando nova coluna no dataset

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),...,Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service,%Population,Deathrate - 10%
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,48.0,0.00,23.06,163.07,700,36.0,...,0.22,87.65,1.0,46.60,20.34,0.380,0.240,0.380,0.48,18.306
1,Albania,EASTERN EUROPE,3581655,28748,124.6,1.26,-4.93,21.52,4500,86.5,...,4.42,74.49,3.0,15.11,5.22,0.232,0.188,0.579,0.05,4.698
2,Algeria,NORTHERN AFRICA,32930091,2381740,13.8,0.04,-0.39,31.00,6000,70.0,...,0.25,96.53,1.0,17.14,4.61,0.101,0.600,0.298,0.50,4.149
3,American Samoa,OCEANIA,57794,199,290.4,58.29,-20.71,9.27,8000,97.0,...,15.00,75.00,2.0,22.46,3.27,0.000,0.000,0.000,0.00,2.943
4,Andorra,WESTERN EUROPE,71201,468,152.1,0.00,6.60,4.05,19000,100.0,...,0.00,97.78,3.0,8.71,6.25,0.000,0.000,0.000,0.00,5.625
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,West Bank,NEAR EAST,2460492,5860,419.9,0.00,2.98,19.62,800,0.0,...,18.97,64.13,3.0,31.67,3.92,0.090,0.280,0.630,0.04,3.528
223,Western Sahara,NORTHERN AFRICA,273008,266000,1.0,0.42,0.00,0.00,0,0.0,...,0.00,99.98,1.0,0.00,0.00,0.000,0.000,0.400,0.00,0.000
224,Yemen,NEAR EAST,21456188,527970,40.6,0.36,0.00,61.50,800,50.2,...,0.24,96.98,1.0,42.89,8.30,0.135,0.472,0.393,0.33,7.470
225,Zambia,SUB-SAHARAN AFRICA,11502010,752614,15.3,0.00,0.00,88.29,800,80.6,...,0.03,92.90,2.0,41.00,19.93,0.220,0.290,0.489,0.18,17.937
226,Zimbabwe,SUB-SAHARAN AFRICA,12236805,390580,31.3,0.00,0.00,67.69,1900,90.7,...,0.34,91.34,2.0,28.01,21.84,0.179,0.243,0.579,0.19,19.656